[package]
name = "Zora"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2", features = ["derive"] }
anyhow = "1.0"
tera = "1.17"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
walkdir = "2.4"
colored = "2.1"
indicatif = "0.17"
chrono = "0.4"